models:
  - "chelsa-w5e5"
variables:
  - "tas"
  - "pr"
  - "rsds"
resolutions:
  - "1800arcsec"

firstyear_inclusive: 2014
lastyear_inclusive: 2014

regions:
  bavaria:
    natural_earth_name: 'Bayern'
    natural_earth_level: 'admin_1_states_provinces'
    minlon: 8
    maxlon: 15
    minlat: 47
    maxlat: 51
  panama:
    natural_earth_name: 'Panama'
    natural_earth_level: 'admin_0_countries'
    minlon: -84
    maxlon: -77
    minlat: 7
    maxlat: 10
#  denmark:
#    natural_earth_name: 'Denmark'
#    natural_earth_level: 'admin_0_countries'
#    minlon: 7
#    maxlon: 12
#    minlat: 54
#    maxlat: 59
