# Author: Konstantin Gregor
# Based off the examples at https://docs.github.com/en/actions/writing-workflows/quickstart

name: Example pipeline
run-name: Setting up conda, running tests, running snakemake including model run
on: [push]
jobs:
  Example-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0} # necessary for conda to work in Github Actions, see https://github.com/marketplace/actions/setup-miniconda#example-3-other-options
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # problem: this takes quite a while (2min). But the nice thing is, this checks that the environment.yml is really
      # containing all that is necessary and simulates setting up the environment from scratch...
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: model-coding-paper
          environment-file: workflow/envs/environment.yml
          python-version: 3.12
          auto-activate-base: false

      - name: Run pytests
        run: |
          PYTHONPATH=. pytest --junitxml=junit/test-results.xml

      - name: Run snakemake
        run: |
          snakemake --use-conda --verbose --cores 1
